# -*- encoding: utf-8 -*-
# stub: raddocs 0.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "raddocs"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Eric Oestrich"]
  s.date = "2016-02-05"
  s.description = "Browse documentation generated by the rspec_api_documentation gem"
  s.email = ["eric@oestrich.org"]
<<<<<<< HEAD
  s.files = ["lib/public/application.css", "lib/public/bootstrap.min.css", "lib/public/codemirror.css", "lib/public/js/codemirror.js", "lib/public/js/jquery-1-7-2.js", "lib/public/js/mode/css/css.js", "lib/public/js/mode/htmlmixed/htmlmixed.js", "lib/public/js/mode/javascript/javascript.js", "lib/public/js/mode/xml/xml.js", "lib/raddocs.rb", "lib/raddocs/app.rb", "lib/raddocs/configuration.rb", "lib/raddocs/middleware.rb", "lib/raddocs/models.rb", "lib/views/example.haml", "lib/views/index.haml", "lib/views/layout.haml", "lib/views/nav.haml"]
=======
  s.files = ["lib/public", "lib/public/application.css", "lib/public/bootstrap.min.css", "lib/public/codemirror.css", "lib/public/js", "lib/public/js/codemirror.js", "lib/public/js/jquery-1-7-2.js", "lib/public/js/mode", "lib/public/js/mode/css", "lib/public/js/mode/css/css.js", "lib/public/js/mode/htmlmixed", "lib/public/js/mode/htmlmixed/htmlmixed.js", "lib/public/js/mode/javascript", "lib/public/js/mode/javascript/javascript.js", "lib/public/js/mode/xml", "lib/public/js/mode/xml/xml.js", "lib/raddocs", "lib/raddocs.rb", "lib/raddocs/app.rb", "lib/raddocs/configuration.rb", "lib/raddocs/middleware.rb", "lib/raddocs/models.rb", "lib/views", "lib/views/example.haml", "lib/views/index.haml", "lib/views/layout.haml", "lib/views/nav.haml"]
>>>>>>> 49965f6d38422dbfd4d2a035746f1b9d2200daf0
  s.homepage = "http://github.com/oestrich/raddocs"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "rspec_api_documentation browser"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.3.0", "~> 1.3"])
      s.add_runtime_dependency(%q<haml>, [">= 4.0.4", "~> 4.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.8.1", "~> 1.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<rack-test>, ["~> 0.6"])
      s.add_development_dependency(%q<capybara>, ["~> 2.3"])
      s.add_development_dependency(%q<rake>, ["~> 10.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.3.0", "~> 1.3"])
      s.add_dependency(%q<haml>, [">= 4.0.4", "~> 4.0"])
      s.add_dependency(%q<json>, [">= 1.8.1", "~> 1.8"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<rack-test>, ["~> 0.6"])
      s.add_dependency(%q<capybara>, ["~> 2.3"])
      s.add_dependency(%q<rake>, ["~> 10.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.3.0", "~> 1.3"])
    s.add_dependency(%q<haml>, [">= 4.0.4", "~> 4.0"])
    s.add_dependency(%q<json>, [">= 1.8.1", "~> 1.8"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<rack-test>, ["~> 0.6"])
    s.add_dependency(%q<capybara>, ["~> 2.3"])
    s.add_dependency(%q<rake>, ["~> 10.0"])
  end
end
